#NAME: Samuel Shen
#EMAIL: sam.shen321@gmail.com
#ID: 405325252

CC = gcc

default:
	gcc -Wall -Wextra -o lab1b-client -lz lab1b-client.c
	gcc -Wall -Wextra -o lab1b-server -lz lab1b-server.c
dist:
	tar -czvf lab1b-405325252.tar.gz lab1b-client.c lab1b-server.c Makefile README
clean:
	rm lab1b-client
	rm lab1b-server
	rm lab1b-405325252.tar.gz
