#NAME: Samuel Shen
#EMAIL: sam.shen321@gmail.com
#ID: 405325252

CC = gcc

dist:
	tar -czvf lab4a-405325252.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

clean:
	rm lab4a-405325252.tar.gz
