# NAME: Samuel Shen
# EMAIL: sam.shen321@gmail.com
# ID: 405325252

CC = gcc

lab1a: lab1a.c
	gcc -Wall -Wextra -o lab1a lab1a.c
clean:
	rm lab1a
	rm lab1a-405325252.tar.gz
dist:
	tar -czvf lab1a-405325252.tar.gz lab1a.c Makefile README
